name: HTML/CSS Autograding
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install html-validate css-validator jsdom cheerio
    
    - name: Run HTML Structure Tests
      run: node tests/structure-tests.js
    
    - name: Run HTML Validation
      run: node tests/html-validator.js
    
    - name: Run CSS Validation
      run: node tests/css-validator.js
    
    - name: Run Comment Quality Tests
      run: node tests/comment-tests.js
    
    - name: Generate Feedback Report
      run: node tests/generate-feedback.js